# Generated by Django 2.2.5 on 2023-03-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=30)),
                ('event_description', models.CharField(blank=True, max_length=100)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('event_result', models.TextField(blank=True, verbose_name='Event Result')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_photo', models.ImageField(blank=True, upload_to='images')),
                ('image_title', models.CharField(max_length=30, verbose_name='TITLE')),
                ('image_description', models.CharField(max_length=100, verbose_name='Image Description')),
                ('upload_dt', models.DateTimeField(auto_now_add=True, verbose_name='upload Date')),
                ('event_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event_info', to='events.Event_info')),
            ],
            options={
                'ordering': ('image_title',),
            },
        ),
    ]
