# Generated by Django 2.2.5 on 2023-03-21 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_image',
            name='event_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_info', to='events.Event_info'),
        ),
    ]
