# Generated by Django 2.2.5 on 2023-01-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertCsv_db',
            fields=[
                ('order_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('order_type', models.CharField(max_length=20)),
                ('store_name', models.CharField(max_length=45)),
                ('licence_num', models.CharField(max_length=20)),
                ('start_address', models.CharField(max_length=120)),
                ('destination_address', models.CharField(max_length=120)),
                ('destination_detailaddress', models.CharField(max_length=80)),
                ('payment_method', models.CharField(max_length=30)),
                ('pickup_ornot', models.CharField(max_length=20)),
                ('order_amount', models.CharField(max_length=45)),
                ('delivery_fee', models.CharField(max_length=45)),
                ('total_amount', models.CharField(max_length=45)),
                ('store_coupon_amount', models.CharField(max_length=45)),
                ('dbt_coupon_amount', models.CharField(max_length=45)),
                ('dbt_coupon_name', models.CharField(max_length=30)),
                ('dbt_coupon_code', models.CharField(max_length=30)),
                ('customer_phone', models.CharField(max_length=45)),
                ('order_date', models.CharField(max_length=20)),
                ('order_time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'statistics_csv',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=8)),
                ('order_amount', models.IntegerField(null=True)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer')),
                ('ordered_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.Store')),
            ],
            options={
                'verbose_name_plural': 'sales',
            },
        ),
    ]
