# Generated by Django 2.2.5 on 2023-01-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insertcsv_db',
            options={'ordering': ['-order_num']},
        ),
    ]
