# Generated by Django 2.2.5 on 2023-04-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_statistics', '0003_answear_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_author',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
