# Generated by Django 2.2.5 on 2023-04-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_statistics', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
