# Generated by Django 2.2.5 on 2023-01-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(default='', max_length=20)),
                ('customer_adress', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
