# Generated by Django 2.2.5 on 2023-01-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(max_length=50)),
                ('store_license_num', models.CharField(blank=True, max_length=20)),
                ('dbt_category', models.CharField(blank=True, choices=[('food_delivery', '음식배달'), ('traditional_market', '전통시장'), ('shopping_mall', '쇼핑몰')], max_length=50)),
                ('business_type', models.CharField(blank=True, max_length=50)),
                ('store_adress', models.CharField(blank=True, max_length=80)),
                ('store_image', models.ImageField(blank=True, null=True, upload_to='store_images')),
                ('menu', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
